// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SercPag_sorting.Context;

#nullable disable

namespace SercPag_sorting.Migrations
{
    [DbContext(typeof(PagingContext))]
    [Migration("20240922132420_ones")]
    partial class ones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SercPag_sorting.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = "002",
                            Email = "ade@xyz.com",
                            Name = "adeyemi"
                        },
                        new
                        {
                            Id = "003",
                            Email = "bala@xyz.com",
                            Name = "bala"
                        },
                        new
                        {
                            Id = "004",
                            Email = "adewumi@xyz.com",
                            Name = "adewumi"
                        },
                        new
                        {
                            Id = "005",
                            Email = "adere@xyz.com",
                            Name = "adere"
                        },
                        new
                        {
                            Id = "006",
                            Email = "adebo@xyz.com",
                            Name = "adebo"
                        },
                        new
                        {
                            Id = "007",
                            Email = "debo@xyz.com",
                            Name = "debo"
                        },
                        new
                        {
                            Id = "008",
                            Email = "bumi@gmail.com",
                            Name = "bumi"
                        },
                        new
                        {
                            Id = "009",
                            Email = "soji@gmail.com",
                            Name = "soji"
                        },
                        new
                        {
                            Id = "010",
                            Email = "taya@gmail.com",
                            Name = "taya"
                        },
                        new
                        {
                            Id = "011",
                            Email = "tomi@gmail.com",
                            Name = "tomi"
                        },
                        new
                        {
                            Id = "012",
                            Email = "dami@gmail.com",
                            Name = "dami"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
